[[about-doc]]
= Про эту документацию
:linkattrs:

В этом разделе содержится краткий обзор документации:
Вы не обязаны читать ее линейно, каждая часть самостоятельна, но вы  будете часто встречать ссылки на другие части.

== Актуальная версия & Copyright Notice
Оригинальная документация на актульную версию доступна здесь http://projectreactor.io/docs/core/release/reference/docs/index.html


=== Оригинальный Copyright
Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.

=== Copyright Перевода
Аналогичен оригиналу

== Contributing to the Documentation
Не требует перевода

== Поддержка
Есть несколько способов (англоязычных)

* Чат сообщества на https://gitter.im/reactor/reactor[Gitter].
* Задать вопрос на  stackoverflow.com
http://stackoverflow.com/tags/project-reactor[`project-reactor`].
* Сообщить о проблеме в Github issues. Отслеживаются :
http://github.com/reactor/reactor-core/issues[reactor-core] (касательно основных функций) и http://github.com/reactor/reactor-addons/issues[reactor-addons]
(касательно вопросов тестирования и адаптеров).


== С чего начать
* Перейдите <<getting-started>>, если хотите сразу посмотреть код.
* Если вы новичек в  _Реактивном программировании_, вам стоит начать с введения <<intro-reactive>>.
* Если вы знакомы с концепциями Reactor и  просто ищете подходящий инстурмент для работы,
но не можете найти правильный оператор посмотрите в <<which-operator>>.
* Что бы подробнее изучить основые функции Реавтора, перейдите в <<core-features>>:
** Подронее в реактивных типах "<<flux>>" and "<<mono>>".
** Как переключать контексты в разделе <<schedulers,Scheduler>>.
** Как обрабатывать ошибки  <<error.handling>>.
* Модульное тестирование с помощью проекта `reactor-test`! Смотрите <<testing>>.
* <<producing>> продвинутый способ создания реактивных источников.
* Другие сложные темы <<advanced>.
