[[getting-started]]
= С чего наачть

Этот раздел содержит информацию для начала работы с Reactor. А именно:

* <<getting-started-introducing-reactor>>
* <<prerequisites>>
* <<getting-started-understanding-bom>>
* <<getting>>

[[getting-started-introducing-reactor]]
== Введение в Reactor
//TODO flesh out, reword. could also be updated on the website
Reactor полностью неблокируемый набор компонент для реактивного программирование под JVM, with
efficient demand management (in the form of managing "backpressure"). Reactor интегрируется с функциональными API Java 8,
 особенно с `CompletableFuture`, `Stream`, и `Duration`. Он предосатвляет составные асинхронные интерфейсы последовательностей
`Flux` (для [N] элементов) и `Mono` (для [0|1] элементов), полностью реализует спецификацию [Reactive Streams](http://www.reactive-streams.org/)
.

Reactor так же подходит для  неблокирующего межпроцессорного взаимодействия с помощью `reactor-netty`.
Reactor Netty предлагает реализацию работы с HTTP (включая Websockets),TCP и UDP
с поддержкой backpressure. Реактивное кодирование и декодирование поддерживается полностью.
Хорошо подходит для микросервисной архитектуры.

[[prerequisites]]
== Требования
Reactor Core работает на `Java 8` и старше.

Реактор имеет транзитивную зависимость от `org.reactive-streams:reactive-streams:1.0.2`.

[NOTE]
====
*Поддержка Android *:

* Reactor 3 официально не поддерживает и не ориентирован на Android (посмотрите на RxJava 2 если вам необходима реактивность).
* Однако, он должен нормально работать начиная с Android SDK 26 (Android O) и выше.
* Мы открыты для изменений, которые положительно повлияют на поддержку Android, но мы не даем никаких гарантий.
 Каждый случай будет требовать индивидуального рассмотрения.
====

[[getting-started-understanding-bom]]
== Понимание BOM
Reactor 3 использует BOM модель `reactor-core 3.0.4`, с `Aluminium` релиза. _(примечание: в переводе версии наверняка устарели)_
Это список версий артифактов, коотрые хооршо работают вместе, несмотря на различные схемы версионирования.

BOM  использует кодовое имя и версию в качестве схемы версионирования. Вот несколько примеров:
[verse]
Aluminium-RELEASE
Californium-BUILD-SNAPSHOT
Aluminium-SR1
Bismuth-RELEASE
Californium-SR32

Кодовые название заменяет традиционное MAJOR.MINOR. Они взяты из  https://en.wikipedia.org/wiki/Periodic_table#Overview[Периодической системы химических элементов], в возрастающем алфавитном порядке.

Квалификаторы (в хронологическом порядке):

* `BUILD-SNAPSHOT`
* `M1`..`N`: Milestones or developer previews
* `RELEASE`: The first GA (General Availability) release in a codename series
* `SR1`..`N`: The subsequent GA releases in a codename series (equivalent to PATCH
number, SR stands for "Service Release").

[[getting]]
== Получение Reactor'а
Как уже говорилось, самый простой способ использовать Reactor в вашем  приложении это использовать BOM
и добавить необходимые зависимости в ваш проект. Обратите внимание, что при добавлении зависимостей
вы не должны указывать версию, что-бы получить правильные версии из BOM спецификации.

Однако, если вы хотите получть определенные версии артефактов, вы можете указать их вручную.
При необходимости вы можете полностью отказаться от спецификации версий через BOM и указывать их вручную.

=== Подключение к  Maven проекту
Концепция BOM поддерживается нативно Maven. Для начала, вам нужно импортировать спецификацию BOM, добавив код
сниппета в ваш `pom.xml`. Если тег  (`dependencyManagement`) уже существует в вашем pom.xml, добавьте только содержимое.

[source,xml]
----
<dependencyManagement> <1>
    <dependencies>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-bom</artifactId>
            <version>Bismuth-RELEASE</version><2>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----
<1> Обратите внимание `dependencyManagement` тег  это не замена тега  `dependencies`, это самостоятельный тег.
<1> Вы читаете перевод, и версия наверняка устарела.

Затем, добавьте нужные зависимости Reactor'а, без тега `<version>`. Например:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core</artifactId> <1>
        <2>
    </dependency>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-test</artifactId> <3>
        <scope>test</scope>
    </dependency>
</dependencies>
----
<1> core библиотека
<2> версия не указана, будет взята из BOM
<3> `reactor-test` инструменты для тестирования реактивных потоков

=== Подключение к Gradle проекту
Gradle не поддерживает Maven BOM спецификации. Но вы можете использовать  Spring плагин для управления зависимостями
https://github.com/spring-gradle-plugins/dependency-management-plugin[gradle-dependency-management].

Вначале, добавьте плагин из Gradle Plugin Portal:

[source,groovy]
----
plugins {
    id "io.spring.dependency-management" version "1.0.6.RELEASE" <1>
}
----
<1> На момент написания версия  1.0.6.RELEASE последняя. Проверяйте обновления!.

Теперь подключите BOM:
[source,groovy]
----
dependencyManagement {
     imports {
          mavenBom "io.projectreactor:reactor-bom:Bismuth-RELEASE"
     }
}
----

Добавьте зависимоть к вашему проекту, бещ номера версии:
[source,groovy]
----
dependencies {
     compile 'io.projectreactor:reactor-core' <1>
}
----
<1> Второе `:` отсутствует. Версия не указана. Она будет взята из спецификации BOM.

=== Вехи и снапшоты
Вехи и снапшоты для разработчиков распространяются через репозиторий Spring Milestones, а не через Maven Central.
Что бы добавить его в свой проект,  скопируйте код снипета в `pom.xml`:

.Milestones in Maven
[source,xml]
----
<repositories>
	<repository>
		<id>spring-milestones</id>
		<name>Spring Milestones Repository</name>
		<url>https://repo.spring.io/milestone</url>
	</repository>
</repositories>
----

Для Gradle используйте:

.Milestones in Gradle
[source,groovy]
----
repositories {
  maven { url 'http://repo.spring.io/milestone' }
  mavenCentral()
}
----

Аналогично, доступны снапшоты в репозитории Spring Snapshot Repository:

.BUILD-SNAPSHOTs in Maven
[source,xml]
----
<repositories>
	<repository>
		<id>spring-snapshots</id>
		<name>Spring Snapshot Repository</name>
		<url>https://repo.spring.io/snapshot</url>
	</repository>
</repositories>
----

.BUILD-SNAPSHOTs in Gradle
[source,groovy]
----
repositories {
  maven { url 'http://repo.spring.io/snapshot' }
  mavenCentral()
}
----
